# Generated by Django 4.2.16 on 2026-07-09 07:49

import apps.settings.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='dark', max_length=10)),
                ('language', models.CharField(choices=[('en', 'English'), ('fa', 'Persian')], default='en', max_length=5)),
                ('default_playback_quality', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('playback_volume', models.FloatField(default=0.7)),
                ('shuffle_enabled', models.BooleanField(default=False)),
                ('repeat_mode', models.CharField(choices=[('none', 'None'), ('one', 'One'), ('all', 'All')], default='none', max_length=5)),
                ('last_playback_position', models.FloatField(blank=True, null=True)),
                ('notification_preferences', models.JSONField(default=apps.settings.models.default_notification_preferences)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_played_song', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.song')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
